workflows:
  react-native-android:
    name: Build APK for Android
    environment:
      vars:
        PACKAGE_NAME: "com.seuprojeto.app"
      node: 18
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
