workflows:
  react-native-android:
    name: Build APK for Android
    environment:
      vars:
        PACKAGE_NAME: "com.xuaum.notificapay"
      node: 18
      java: 17
      groups:
        - default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Set up Android SDK
        script: |
          sdkmanager "build-tools;33.0.0" "platforms;android-33"
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
